### ISSUE TITLE
How to use it in fragment？

### ISSUE THREAD

**Issue by kyze8439690** [sockeqwe/SwipeBack#1]
Great library, I think this library is better than https://github.com/Issacw0ng/SwipeBackLayout because it has an indicator and lots of custom options, but how can I use this library in fragment?For example, in onCreateView, how can I get the swipeback view?

**Comment by Logan676** [comment]
@sockeqwe thanks for you awesome library, which exactly what I am looking for. I have implemented the  swipe back feature via a ViewPagerActivity just as your examples show, and it works really cool.

But I was confused that how to handle the swipe back callback. 

For instance, I have a ViewPagerActivity which has two Fragments, e.g. FragmentA and FragmentB. I have configured the FragmentA to support swipe back feature, and FragmentA show a directory structure.

My problem is, when clicked into a sub directory in FragmentA, then swipe back, unfortunately it finished the ViewPagerActivity instead of navigate back to the parent directory in FragmentA. So I wonder how to handle the swipe back callback, does it in `onBackPressed`?

**Comment by sockeqwe** [comment]
You have to provide your own **callback**  implementation:

```java
SwipeBack.attach(this, Position.LEFT)
        .setSwipeBackTransformer(new MyCallbackTransformer());
```

Have a look here:
https://github.com/sockeqwe/SwipeBack/tree/master/library/src/com/hannesdorfmann/swipeback/transformer

**Comment by Logan676** [comment]
Thanks for such a fast responding, now I know how to implement it.
